@startuml
participant Actor
Actor -> AbstractAdvisorAutoProxyCreator : getAdvicesAndAdvisorsForBean
activate AbstractAdvisorAutoProxyCreator
AbstractAdvisorAutoProxyCreator -> AbstractAdvisorAutoProxyCreator : findEligibleAdvisors
activate AbstractAdvisorAutoProxyCreator
AbstractAdvisorAutoProxyCreator -> AbstractAdvisorAutoProxyCreator : findCandidateAdvisors
activate AbstractAdvisorAutoProxyCreator
AbstractAdvisorAutoProxyCreator -> BeanFactoryAdvisorRetrievalHelper : findAdvisorBeans
activate BeanFactoryAdvisorRetrievalHelper
BeanFactoryAdvisorRetrievalHelper --> AbstractAdvisorAutoProxyCreator
deactivate BeanFactoryAdvisorRetrievalHelper
AbstractAdvisorAutoProxyCreator -> AnnotationAwareAspectJAutoProxyCreator : findCandidateAdvisors
activate AnnotationAwareAspectJAutoProxyCreator
AnnotationAwareAspectJAutoProxyCreator --> AbstractAdvisorAutoProxyCreator
deactivate AnnotationAwareAspectJAutoProxyCreator
AbstractAdvisorAutoProxyCreator --> AbstractAdvisorAutoProxyCreator
deactivate AbstractAdvisorAutoProxyCreator
AbstractAdvisorAutoProxyCreator -> AbstractAdvisorAutoProxyCreator : findAdvisorsThatCanApply
activate AbstractAdvisorAutoProxyCreator
AbstractAdvisorAutoProxyCreator -> AopUtils : findAdvisorsThatCanApply
activate AopUtils
AopUtils --> AbstractAdvisorAutoProxyCreator
deactivate AopUtils
AbstractAdvisorAutoProxyCreator --> AbstractAdvisorAutoProxyCreator
deactivate AbstractAdvisorAutoProxyCreator
AbstractAdvisorAutoProxyCreator -> AbstractAdvisorAutoProxyCreator : extendAdvisors
activate AbstractAdvisorAutoProxyCreator
AbstractAdvisorAutoProxyCreator -> AspectJAwareAdvisorAutoProxyCreator : extendAdvisors
activate AspectJAwareAdvisorAutoProxyCreator
AspectJAwareAdvisorAutoProxyCreator --> AbstractAdvisorAutoProxyCreator
deactivate AspectJAwareAdvisorAutoProxyCreator
AbstractAdvisorAutoProxyCreator --> AbstractAdvisorAutoProxyCreator
deactivate AbstractAdvisorAutoProxyCreator
AbstractAdvisorAutoProxyCreator -> AbstractAdvisorAutoProxyCreator : sortAdvisors
activate AbstractAdvisorAutoProxyCreator
AbstractAdvisorAutoProxyCreator -> AspectJAwareAdvisorAutoProxyCreator : sortAdvisors
activate AspectJAwareAdvisorAutoProxyCreator
AspectJAwareAdvisorAutoProxyCreator --> AbstractAdvisorAutoProxyCreator
deactivate AspectJAwareAdvisorAutoProxyCreator
AbstractAdvisorAutoProxyCreator --> AbstractAdvisorAutoProxyCreator
deactivate AbstractAdvisorAutoProxyCreator
AbstractAdvisorAutoProxyCreator --> AbstractAdvisorAutoProxyCreator
deactivate AbstractAdvisorAutoProxyCreator
return
@enduml

material