version: '3'

services:
  #zookeeper:
  #  image: zookeeper
  #  ports:
  #    - 2181:2181
  admin:
    image: apache/dubbo-admin
    external_links:
      - zoo1
    ports:
      - 8080:8080
    environment:
      - admin.registry.address=zookeeper://zoo1:2181
      - admin.config-center=zookeeper://zoo1:2181
      - admin.metadata-report.address=zookeeper://zoo1:2181
networks:
  default:
    external:
      name: zookeeper_network