version: '3'

services:
  #zookeeper:
  #  image: zookeeper
  #  ports:
  #    - 2181:2181
  admin:
    image: apache/dubbo-admin
    networks:
      - zookeeper
    ports:
      - 8080:8080
    environment:
      - admin.registry.address=zookeeper://zookeeper:2181
      - admin.config-center=zookeeper://zookeeper:2181
      - admin.metadata-report.address=zookeeper://zookeeper:2181
networks:
  zookeeper:
    external: true