version: '2'
services:
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - "9092:9092"
    networks:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181,zookeeper:2182,zookeeper:2183
      # modify the KAFKA_ADVERTISED_HOST_NAME in docker-compose.yml to match your docker host IP (Note: Do not use localhost or 127.0.0.1 as the host ip if you want to run multiple brokers.)
      KAFKA_ADVERTISED_HOST_NAME: localhost
networks:
  zookeeper:
    external: true

