version: '3.8'
services:
  kafka:
    image: bitnami/kafka:4.0.0
    container_name: kafka-broker
    ports:
      - "9092:9092"        # 明文端口
      - "9093:9093"        # SASL_SSL 端口（按需启用）
    environment:
      # KRaft 模式配置（二选一）
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      
      # 或 ZooKeeper 兼容模式（二选一）
      # KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      
      # 基础参数
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://${HOST_IP}:9092"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      
      # 生产环境必调参数
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3     # 副本因子
      KAFKA_CFG_NUM_PARTITIONS: 6                 # 分区数
      ALLOW_PLAINTEXT_LISTENER: "yes"             # 允许明文传输（测试用）
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - kafka-net

# 若使用 ZooKeeper 模式需保留此服务
  zookeeper:
    image: bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    volumes:
      - zookeeper_data:/bitnami/zookeeper

volumes:
  kafka_data:
  zookeeper_data:
networks:
  kafka-net:
    driver: bridge
