spring:
    cloud:
        zookeeper:
            connect-string: localhost:2181
            config:
                enabled: true
                root: /discovery/config
                default-context: application
                profile-separator: ','
                name: zk-config-center
                watcher:
                    enabled: true