package com.louis.coub.escustomer.collect.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.Collections;
import javax.annotation.Generated;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2020-8-27")
public class BusinessLogData implements org.apache.thrift.TBase<BusinessLogData, BusinessLogData._Fields>, java.io.Serializable, Cloneable, Comparable<BusinessLogData> {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BusinessLogData");

    private static final org.apache.thrift.protocol.TField PRO_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("proCode", org.apache.thrift.protocol.TType.STRING, (short)1);
    private static final org.apache.thrift.protocol.TField APP_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("appCode", org.apache.thrift.protocol.TType.STRING, (short)2);
    private static final org.apache.thrift.protocol.TField INST_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("instCode", org.apache.thrift.protocol.TType.STRING, (short)3);
    private static final org.apache.thrift.protocol.TField IP_FIELD_DESC = new org.apache.thrift.protocol.TField("ip", org.apache.thrift.protocol.TType.STRING, (short)4);
    private static final org.apache.thrift.protocol.TField PID_FIELD_DESC = new org.apache.thrift.protocol.TField("pid", org.apache.thrift.protocol.TType.I32, (short)5);
    private static final org.apache.thrift.protocol.TField LOG_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("logList", org.apache.thrift.protocol.TType.LIST, (short)6);
    private static final org.apache.thrift.protocol.TField TOTAL_SIZE_FIELD_DESC = new org.apache.thrift.protocol.TField("totalSize", org.apache.thrift.protocol.TType.I64, (short)7);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
        schemes.put(StandardScheme.class, new BusinessLogDataStandardSchemeFactory());
        schemes.put(TupleScheme.class, new BusinessLogDataTupleSchemeFactory());
    }

    public String proCode; // required
    public String appCode; // required
    public String instCode; // required
    public String ip; // required
    public int pid; // required
    public List<BusinessLog> logList; // required
    public long totalSize; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        PRO_CODE((short)1, "proCode"),
        APP_CODE((short)2, "appCode"),
        INST_CODE((short)3, "instCode"),
        IP((short)4, "ip"),
        PID((short)5, "pid"),
        LOG_LIST((short)6, "logList"),
        TOTAL_SIZE((short)7, "totalSize");

        private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

        static {
            for (_Fields field : EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        public static _Fields findByThriftId(int fieldId) {
            switch(fieldId) {
                case 1: // PRO_CODE
                    return PRO_CODE;
                case 2: // APP_CODE
                    return APP_CODE;
                case 3: // INST_CODE
                    return INST_CODE;
                case 4: // IP
                    return IP;
                case 5: // PID
                    return PID;
                case 6: // LOG_LIST
                    return LOG_LIST;
                case 7: // TOTAL_SIZE
                    return TOTAL_SIZE;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId) {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        public static _Fields findByName(String name) {
            return byName.get(name);
        }

        private final short _thriftId;
        private final String _fieldName;

        _Fields(short thriftId, String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        public short getThriftFieldId() {
            return _thriftId;
        }

        public String getFieldName() {
            return _fieldName;
        }
    }

    // isset id assignments
    private static final int __PID_ISSET_ID = 0;
    private static final int __TOTALSIZE_ISSET_ID = 1;
    private byte __isset_bitfield = 0;
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
        Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.PRO_CODE, new org.apache.thrift.meta_data.FieldMetaData("proCode", org.apache.thrift.TFieldRequirementType.REQUIRED,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        tmpMap.put(_Fields.APP_CODE, new org.apache.thrift.meta_data.FieldMetaData("appCode", org.apache.thrift.TFieldRequirementType.REQUIRED,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        tmpMap.put(_Fields.INST_CODE, new org.apache.thrift.meta_data.FieldMetaData("instCode", org.apache.thrift.TFieldRequirementType.REQUIRED,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        tmpMap.put(_Fields.IP, new org.apache.thrift.meta_data.FieldMetaData("ip", org.apache.thrift.TFieldRequirementType.REQUIRED,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        tmpMap.put(_Fields.PID, new org.apache.thrift.meta_data.FieldMetaData("pid", org.apache.thrift.TFieldRequirementType.REQUIRED,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
        tmpMap.put(_Fields.LOG_LIST, new org.apache.thrift.meta_data.FieldMetaData("logList", org.apache.thrift.TFieldRequirementType.REQUIRED,
                new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
                        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT            , "BusinessLog"))));
        tmpMap.put(_Fields.TOTAL_SIZE, new org.apache.thrift.meta_data.FieldMetaData("totalSize", org.apache.thrift.TFieldRequirementType.REQUIRED,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
        metaDataMap = Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BusinessLogData.class, metaDataMap);
    }

    public BusinessLogData() {
    }

    public BusinessLogData(
            String proCode,
            String appCode,
            String instCode,
            String ip,
            int pid,
            List<BusinessLog> logList,
            long totalSize)
    {
        this();
        this.proCode = proCode;
        this.appCode = appCode;
        this.instCode = instCode;
        this.ip = ip;
        this.pid = pid;
        setPidIsSet(true);
        this.logList = logList;
        this.totalSize = totalSize;
        setTotalSizeIsSet(true);
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public BusinessLogData(BusinessLogData other) {
        __isset_bitfield = other.__isset_bitfield;
        if (other.isSetProCode()) {
            this.proCode = other.proCode;
        }
        if (other.isSetAppCode()) {
            this.appCode = other.appCode;
        }
        if (other.isSetInstCode()) {
            this.instCode = other.instCode;
        }
        if (other.isSetIp()) {
            this.ip = other.ip;
        }
        this.pid = other.pid;
        if (other.isSetLogList()) {
            List<BusinessLog> __this__logList = new ArrayList<BusinessLog>(other.logList.size());
            for (BusinessLog other_element : other.logList) {
                __this__logList.add(other_element);
            }
            this.logList = __this__logList;
        }
        this.totalSize = other.totalSize;
    }

    public BusinessLogData deepCopy() {
        return new BusinessLogData(this);
    }

    @Override
    public void clear() {
        this.proCode = null;
        this.appCode = null;
        this.instCode = null;
        this.ip = null;
        setPidIsSet(false);
        this.pid = 0;
        this.logList = null;
        setTotalSizeIsSet(false);
        this.totalSize = 0;
    }

    public String getProCode() {
        return this.proCode;
    }

    public BusinessLogData setProCode(String proCode) {
        this.proCode = proCode;
        return this;
    }

    public void unsetProCode() {
        this.proCode = null;
    }

    /** Returns true if field proCode is set (has been assigned a value) and false otherwise */
    public boolean isSetProCode() {
        return this.proCode != null;
    }

    public void setProCodeIsSet(boolean value) {
        if (!value) {
            this.proCode = null;
        }
    }

    public String getAppCode() {
        return this.appCode;
    }

    public BusinessLogData setAppCode(String appCode) {
        this.appCode = appCode;
        return this;
    }

    public void unsetAppCode() {
        this.appCode = null;
    }

    /** Returns true if field appCode is set (has been assigned a value) and false otherwise */
    public boolean isSetAppCode() {
        return this.appCode != null;
    }

    public void setAppCodeIsSet(boolean value) {
        if (!value) {
            this.appCode = null;
        }
    }

    public String getInstCode() {
        return this.instCode;
    }

    public BusinessLogData setInstCode(String instCode) {
        this.instCode = instCode;
        return this;
    }

    public void unsetInstCode() {
        this.instCode = null;
    }

    /** Returns true if field instCode is set (has been assigned a value) and false otherwise */
    public boolean isSetInstCode() {
        return this.instCode != null;
    }

    public void setInstCodeIsSet(boolean value) {
        if (!value) {
            this.instCode = null;
        }
    }

    public String getIp() {
        return this.ip;
    }

    public BusinessLogData setIp(String ip) {
        this.ip = ip;
        return this;
    }

    public void unsetIp() {
        this.ip = null;
    }

    /** Returns true if field ip is set (has been assigned a value) and false otherwise */
    public boolean isSetIp() {
        return this.ip != null;
    }

    public void setIpIsSet(boolean value) {
        if (!value) {
            this.ip = null;
        }
    }

    public int getPid() {
        return this.pid;
    }

    public BusinessLogData setPid(int pid) {
        this.pid = pid;
        setPidIsSet(true);
        return this;
    }

    public void unsetPid() {
        __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PID_ISSET_ID);
    }

    /** Returns true if field pid is set (has been assigned a value) and false otherwise */
    public boolean isSetPid() {
        return EncodingUtils.testBit(__isset_bitfield, __PID_ISSET_ID);
    }

    public void setPidIsSet(boolean value) {
        __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PID_ISSET_ID, value);
    }

    public int getLogListSize() {
        return (this.logList == null) ? 0 : this.logList.size();
    }

    public java.util.Iterator<BusinessLog> getLogListIterator() {
        return (this.logList == null) ? null : this.logList.iterator();
    }

    public void addToLogList(BusinessLog elem) {
        if (this.logList == null) {
            this.logList = new ArrayList<BusinessLog>();
        }
        this.logList.add(elem);
    }

    public List<BusinessLog> getLogList() {
        return this.logList;
    }

    public BusinessLogData setLogList(List<BusinessLog> logList) {
        this.logList = logList;
        return this;
    }

    public void unsetLogList() {
        this.logList = null;
    }

    /** Returns true if field logList is set (has been assigned a value) and false otherwise */
    public boolean isSetLogList() {
        return this.logList != null;
    }

    public void setLogListIsSet(boolean value) {
        if (!value) {
            this.logList = null;
        }
    }

    public long getTotalSize() {
        return this.totalSize;
    }

    public BusinessLogData setTotalSize(long totalSize) {
        this.totalSize = totalSize;
        setTotalSizeIsSet(true);
        return this;
    }

    public void unsetTotalSize() {
        __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TOTALSIZE_ISSET_ID);
    }

    /** Returns true if field totalSize is set (has been assigned a value) and false otherwise */
    public boolean isSetTotalSize() {
        return EncodingUtils.testBit(__isset_bitfield, __TOTALSIZE_ISSET_ID);
    }

    public void setTotalSizeIsSet(boolean value) {
        __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TOTALSIZE_ISSET_ID, value);
    }

    public void setFieldValue(_Fields field, Object value) {
        switch (field) {
            case PRO_CODE:
                if (value == null) {
                    unsetProCode();
                } else {
                    setProCode((String)value);
                }
                break;

            case APP_CODE:
                if (value == null) {
                    unsetAppCode();
                } else {
                    setAppCode((String)value);
                }
                break;

            case INST_CODE:
                if (value == null) {
                    unsetInstCode();
                } else {
                    setInstCode((String)value);
                }
                break;

            case IP:
                if (value == null) {
                    unsetIp();
                } else {
                    setIp((String)value);
                }
                break;

            case PID:
                if (value == null) {
                    unsetPid();
                } else {
                    setPid((Integer)value);
                }
                break;

            case LOG_LIST:
                if (value == null) {
                    unsetLogList();
                } else {
                    setLogList((List<BusinessLog>)value);
                }
                break;

            case TOTAL_SIZE:
                if (value == null) {
                    unsetTotalSize();
                } else {
                    setTotalSize((Long)value);
                }
                break;

        }
    }

    public Object getFieldValue(_Fields field) {
        switch (field) {
            case PRO_CODE:
                return getProCode();

            case APP_CODE:
                return getAppCode();

            case INST_CODE:
                return getInstCode();

            case IP:
                return getIp();

            case PID:
                return Integer.valueOf(getPid());

            case LOG_LIST:
                return getLogList();

            case TOTAL_SIZE:
                return Long.valueOf(getTotalSize());

        }
        throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
        if (field == null) {
            throw new IllegalArgumentException();
        }

        switch (field) {
            case PRO_CODE:
                return isSetProCode();
            case APP_CODE:
                return isSetAppCode();
            case INST_CODE:
                return isSetInstCode();
            case IP:
                return isSetIp();
            case PID:
                return isSetPid();
            case LOG_LIST:
                return isSetLogList();
            case TOTAL_SIZE:
                return isSetTotalSize();
        }
        throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
        if (that == null)
            return false;
        if (that instanceof BusinessLogData)
            return this.equals((BusinessLogData)that);
        return false;
    }

    public boolean equals(BusinessLogData that) {
        if (that == null)
            return false;

        boolean this_present_proCode = true && this.isSetProCode();
        boolean that_present_proCode = true && that.isSetProCode();
        if (this_present_proCode || that_present_proCode) {
            if (!(this_present_proCode && that_present_proCode))
                return false;
            if (!this.proCode.equals(that.proCode))
                return false;
        }

        boolean this_present_appCode = true && this.isSetAppCode();
        boolean that_present_appCode = true && that.isSetAppCode();
        if (this_present_appCode || that_present_appCode) {
            if (!(this_present_appCode && that_present_appCode))
                return false;
            if (!this.appCode.equals(that.appCode))
                return false;
        }

        boolean this_present_instCode = true && this.isSetInstCode();
        boolean that_present_instCode = true && that.isSetInstCode();
        if (this_present_instCode || that_present_instCode) {
            if (!(this_present_instCode && that_present_instCode))
                return false;
            if (!this.instCode.equals(that.instCode))
                return false;
        }

        boolean this_present_ip = true && this.isSetIp();
        boolean that_present_ip = true && that.isSetIp();
        if (this_present_ip || that_present_ip) {
            if (!(this_present_ip && that_present_ip))
                return false;
            if (!this.ip.equals(that.ip))
                return false;
        }

        boolean this_present_pid = true;
        boolean that_present_pid = true;
        if (this_present_pid || that_present_pid) {
            if (!(this_present_pid && that_present_pid))
                return false;
            if (this.pid != that.pid)
                return false;
        }

        boolean this_present_logList = true && this.isSetLogList();
        boolean that_present_logList = true && that.isSetLogList();
        if (this_present_logList || that_present_logList) {
            if (!(this_present_logList && that_present_logList))
                return false;
            if (!this.logList.equals(that.logList))
                return false;
        }

        boolean this_present_totalSize = true;
        boolean that_present_totalSize = true;
        if (this_present_totalSize || that_present_totalSize) {
            if (!(this_present_totalSize && that_present_totalSize))
                return false;
            if (this.totalSize != that.totalSize)
                return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        List<Object> list = new ArrayList<Object>();

        boolean present_proCode = true && (isSetProCode());
        list.add(present_proCode);
        if (present_proCode)
            list.add(proCode);

        boolean present_appCode = true && (isSetAppCode());
        list.add(present_appCode);
        if (present_appCode)
            list.add(appCode);

        boolean present_instCode = true && (isSetInstCode());
        list.add(present_instCode);
        if (present_instCode)
            list.add(instCode);

        boolean present_ip = true && (isSetIp());
        list.add(present_ip);
        if (present_ip)
            list.add(ip);

        boolean present_pid = true;
        list.add(present_pid);
        if (present_pid)
            list.add(pid);

        boolean present_logList = true && (isSetLogList());
        list.add(present_logList);
        if (present_logList)
            list.add(logList);

        boolean present_totalSize = true;
        list.add(present_totalSize);
        if (present_totalSize)
            list.add(totalSize);

        return list.hashCode();
    }

    @Override
    public int compareTo(BusinessLogData other) {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = Boolean.valueOf(isSetProCode()).compareTo(other.isSetProCode());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetProCode()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.proCode, other.proCode);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetAppCode()).compareTo(other.isSetAppCode());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetAppCode()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.appCode, other.appCode);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetInstCode()).compareTo(other.isSetInstCode());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetInstCode()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.instCode, other.instCode);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetIp()).compareTo(other.isSetIp());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetIp()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ip, other.ip);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetPid()).compareTo(other.isSetPid());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetPid()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pid, other.pid);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetLogList()).compareTo(other.isSetLogList());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetLogList()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.logList, other.logList);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetTotalSize()).compareTo(other.isSetTotalSize());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetTotalSize()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.totalSize, other.totalSize);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    public _Fields fieldForId(int fieldId) {
        return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
        schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
        schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BusinessLogData(");
        boolean first = true;

        sb.append("proCode:");
        if (this.proCode == null) {
            sb.append("null");
        } else {
            sb.append(this.proCode);
        }
        first = false;
        if (!first) sb.append(", ");
        sb.append("appCode:");
        if (this.appCode == null) {
            sb.append("null");
        } else {
            sb.append(this.appCode);
        }
        first = false;
        if (!first) sb.append(", ");
        sb.append("instCode:");
        if (this.instCode == null) {
            sb.append("null");
        } else {
            sb.append(this.instCode);
        }
        first = false;
        if (!first) sb.append(", ");
        sb.append("ip:");
        if (this.ip == null) {
            sb.append("null");
        } else {
            sb.append(this.ip);
        }
        first = false;
        if (!first) sb.append(", ");
        sb.append("pid:");
        sb.append(this.pid);
        first = false;
        if (!first) sb.append(", ");
        sb.append("logList:");
        if (this.logList == null) {
            sb.append("null");
        } else {
            sb.append(this.logList);
        }
        first = false;
        if (!first) sb.append(", ");
        sb.append("totalSize:");
        sb.append(this.totalSize);
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate() throws TException {
        // check for required fields
        if (proCode == null) {
            throw new TProtocolException("Required field 'proCode' was not present! Struct: " + toString());
        }
        if (appCode == null) {
            throw new TProtocolException("Required field 'appCode' was not present! Struct: " + toString());
        }
        if (instCode == null) {
            throw new TProtocolException("Required field 'instCode' was not present! Struct: " + toString());
        }
        if (ip == null) {
            throw new TProtocolException("Required field 'ip' was not present! Struct: " + toString());
        }
        // alas, we cannot check 'pid' because it's a primitive and you chose the non-beans generator.
        if (logList == null) {
            throw new TProtocolException("Required field 'logList' was not present! Struct: " + toString());
        }
        // alas, we cannot check 'totalSize' because it's a primitive and you chose the non-beans generator.
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
        try {
            // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
            __isset_bitfield = 0;
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class BusinessLogDataStandardSchemeFactory implements SchemeFactory {
        public BusinessLogDataStandardScheme getScheme() {
            return new BusinessLogDataStandardScheme();
        }
    }

    private static class BusinessLogDataStandardScheme extends StandardScheme<BusinessLogData> {

        public void read(org.apache.thrift.protocol.TProtocol iprot, BusinessLogData struct) throws TException {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true)
            {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // PRO_CODE
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.proCode = iprot.readString();
                            struct.setProCodeIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // APP_CODE
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.appCode = iprot.readString();
                            struct.setAppCodeIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 3: // INST_CODE
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.instCode = iprot.readString();
                            struct.setInstCodeIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 4: // IP
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.ip = iprot.readString();
                            struct.setIpIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 5: // PID
                        if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                            struct.pid = iprot.readI32();
                            struct.setPidIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 6: // LOG_LIST
                        if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                            {
                                org.apache.thrift.protocol.TList _list42 = iprot.readListBegin();
                                struct.logList = new ArrayList<BusinessLog>(_list42.size);
                                BusinessLog _elem43;
                                for (int _i44 = 0; _i44 < _list42.size; ++_i44)
                                {
                                    _elem43 = new BusinessLog();
                                    _elem43.read(iprot);
                                    struct.logList.add(_elem43);
                                }
                                iprot.readListEnd();
                            }
                            struct.setLogListIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 7: // TOTAL_SIZE
                        if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
                            struct.totalSize = iprot.readI64();
                            struct.setTotalSizeIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            if (!struct.isSetPid()) {
                throw new TProtocolException("Required field 'pid' was not found in serialized data! Struct: " + toString());
            }
            if (!struct.isSetTotalSize()) {
                throw new TProtocolException("Required field 'totalSize' was not found in serialized data! Struct: " + toString());
            }
            struct.validate();
        }

        public void write(org.apache.thrift.protocol.TProtocol oprot, BusinessLogData struct) throws TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.proCode != null) {
                oprot.writeFieldBegin(PRO_CODE_FIELD_DESC);
                oprot.writeString(struct.proCode);
                oprot.writeFieldEnd();
            }
            if (struct.appCode != null) {
                oprot.writeFieldBegin(APP_CODE_FIELD_DESC);
                oprot.writeString(struct.appCode);
                oprot.writeFieldEnd();
            }
            if (struct.instCode != null) {
                oprot.writeFieldBegin(INST_CODE_FIELD_DESC);
                oprot.writeString(struct.instCode);
                oprot.writeFieldEnd();
            }
            if (struct.ip != null) {
                oprot.writeFieldBegin(IP_FIELD_DESC);
                oprot.writeString(struct.ip);
                oprot.writeFieldEnd();
            }
            oprot.writeFieldBegin(PID_FIELD_DESC);
            oprot.writeI32(struct.pid);
            oprot.writeFieldEnd();
            if (struct.logList != null) {
                oprot.writeFieldBegin(LOG_LIST_FIELD_DESC);
                {
                    oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.logList.size()));
                    for (BusinessLog _iter45 : struct.logList)
                    {
                        _iter45.write(oprot);
                    }
                    oprot.writeListEnd();
                }
                oprot.writeFieldEnd();
            }
            oprot.writeFieldBegin(TOTAL_SIZE_FIELD_DESC);
            oprot.writeI64(struct.totalSize);
            oprot.writeFieldEnd();
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

    private static class BusinessLogDataTupleSchemeFactory implements SchemeFactory {
        public BusinessLogDataTupleScheme getScheme() {
            return new BusinessLogDataTupleScheme();
        }
    }

    private static class BusinessLogDataTupleScheme extends TupleScheme<BusinessLogData> {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, BusinessLogData struct) throws TException {
            TTupleProtocol oprot = (TTupleProtocol) prot;
            oprot.writeString(struct.proCode);
            oprot.writeString(struct.appCode);
            oprot.writeString(struct.instCode);
            oprot.writeString(struct.ip);
            oprot.writeI32(struct.pid);
            {
                oprot.writeI32(struct.logList.size());
                for (BusinessLog _iter46 : struct.logList)
                {
                    _iter46.write(oprot);
                }
            }
            oprot.writeI64(struct.totalSize);
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, BusinessLogData struct) throws TException {
            TTupleProtocol iprot = (TTupleProtocol) prot;
            struct.proCode = iprot.readString();
            struct.setProCodeIsSet(true);
            struct.appCode = iprot.readString();
            struct.setAppCodeIsSet(true);
            struct.instCode = iprot.readString();
            struct.setInstCodeIsSet(true);
            struct.ip = iprot.readString();
            struct.setIpIsSet(true);
            struct.pid = iprot.readI32();
            struct.setPidIsSet(true);
            {
                org.apache.thrift.protocol.TList _list47 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
                struct.logList = new ArrayList<BusinessLog>(_list47.size);
                BusinessLog _elem48;
                for (int _i49 = 0; _i49 < _list47.size; ++_i49)
                {
                    _elem48 = new BusinessLog();
                    _elem48.read(iprot);
                    struct.logList.add(_elem48);
                }
            }
            struct.setLogListIsSet(true);
            struct.totalSize = iprot.readI64();
            struct.setTotalSizeIsSet(true);
        }
    }

}