version: '3.1'
services:
  kafka-manager:
    image: sheepkiller/kafka-manager:stable
    restart: unless-stopped
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "172.17.158.130:2181,172.17.158.129:2181,172.17.158.132:2181"
      APPLICATION_SECRET: "hd!QAZ2wsx"
    volumes:
      -  /var/run/docker.sock:/var/run/docker.sock