version: '3.1'
services:
  kafka-manager: # Kafka 图形管理界面
    image: sheepkiller/kafka-manager:latest
    restart: unless-stopped
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
      - "9000:9000"
  #  links:            # 连接本compose文件创建的container
    external_links:   # 连接外部compose文件创建的container
      - zoo1
      - zoo2
      - zoo3
      - kafka1
      - kafka2
      - kafka3
    environment:
      ZK_HOSTS: 172.18.0.2:2181,172.18.0.3:2181,172.18.0.4:2181
      KAFKA_BROKERS: kafka1:9092,kafka2:9093,kafka3:9094

networks:
  default:
    external:
      name: zookeeper_network