server:
  port: 8081
project:
  jenkins:
    server-uri: http://localhost:8080
    username: root
    password: Root
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    platform: MYSQL