version: '3.7'
services:
    master:
        image: redis:5.0.5-alpine
        container_name: redis-master
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
            - 6379:6379
