spring:
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
  datasource:
    platform: MYSQL
    url: jdbc:mysql://localhost:3306/mybatis_source?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: "!qaz@wsx"
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
logging:
  level:
    com:
      baomidou: debug
server:
  port: 8088

