spring:
  datasource:
    platform: MYSQL
    url: jdbc:mysql://localhost:3306/louis-coub?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "!qaz@wsx"
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
logging:
  level:
    com.baomidou: debug
    org.springframework.orm: debug
    org.springframework.jdbc: debug
    com.louis.mybatis.tk: debug
server:
  port: 8088
mybatis-plus:
  mapper-locations: classpath*:/base/*.xml
  type-aliases-package: com.louis.mybatis.tk.entry
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


