version: '3.0'
services:
  louis_jenkins:
    image:  jenkins/jenkins:lts
    container_name: louis_jenkins
    ports:
      - 8080:8080
      - 50000:50000
    user: '0'
#    volumes:
#      - ./jenkins_home/:/var/jenkins_home/
