
logging:
  level:
    org.springframework: info
server:
  port: 8081
spring:
  main:
   log-startup-info: true
   lazy-initialization: true
   banner-mode: console

  datasource:
    platform: MYSQL
    url: jdbc:mysql://localhost:3306/louis-coub?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: "!QAZ2wsx"
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev


